# Yeoman with some generators and prerequisites
FROM cthulhu666/yeoman:1.6.0

MAINTAINER Jakub Głuszecki <jakub.gluszecki@gmail.com>

RUN sudo npm install -g --silent gulp@3.9.0 \
    generator-gulp-webapp@1.0.3 generator-gulp-angular@1.0.0

